# Generated by Django 5.0.6 on 2024-06-03 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mir_handler", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mirfilemodel",
            name="json_file",
        ),
    ]
